on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '16'
        cache: 'yarn'

    - run: yarn install
    - run: yarn test